// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjlwfslgqwbcpfhgsikf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbHdmc2xncXdiY3BmaGdzaWtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTE4NzIsImV4cCI6MjA2NjY2Nzg3Mn0.xy-mIOgVUAI-dK-GWBurmrzMUzsPLCylEd6Tr7Uxacc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);